### ISSUE TITLE
API keys

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/bienapi#5]
I think it'd be better to have separate API keys for each person - one key for everything seems to me the same as no keys at all - so might as well have a sep. key per person, then would give better sense of usage per person, and can throttle people using it "too" heavily

**Comment by ojalaquellueva** [comment]
Agree with separate API key for each person.

-Brad

**Comment by sckott** [comment]
cool. 

may play around with a route (.e,g. `/token`) for users to request keys to have a fast turn around time between user wanting to use the API, and actually being able to use it.

**Comment by sckott** [comment]
should probably switch to Bearer format https://tools.ietf.org/html/rfc6750 since seems like even though we're not doing OAuth, we can still use bearer setup without that https://stackoverflow.com/a/34022350/1091766

**Comment by sckott** [comment]
jwt gem 

http://www.rubydoc.info/gems/jwt/2.0.0

https://auth0.com/blog/ruby-authentication-secure-rack-apps-with-jwt/

**Comment by sckott** [comment]
jwt as api keys https://auth0.com/blog/using-json-web-tokens-as-api-keys/

middleware only on some routes https://stackoverflow.com/questions/920719/how-do-i-use-a-rack-middleware-only-for-certain-paths
